name: Build CDK Extension

on:
  push:
    branches: [main]
    paths:
      - "extensions/cdk/**"

jobs:
  buildExtension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: set_var
        run: |
          export content=`cat ./extensions/cdk/package.json | jq -r .version`
          echo "tagVersion=$content" >> $GITHUB_ENV
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: extensions/cdk
          push: true
          tags: serverless/cdk:latest,serverless/cdk:${{ env.tagVersion}}
          platforms: linux/amd64,linux/arm64
          file: Dockerfile